// Shared content for every design, so only presentation varies.
// Each design page loads this with <script src="../../recipes.js"></script>.
const RECIPES = [
  {
    slug: "sourdough",
    name: "Country Sourdough",
    tagline: "Crackling crust, open crumb, tangy and slow.",
    time: "24 hrs (30 min hands-on)",
    yield: "1 loaf",
    difficulty: "Intermediate",
    ingredients: [
      "450 g bread flour",
      "50 g whole wheat flour",
      "375 g water",
      "100 g active starter",
      "10 g fine sea salt",
    ],
    steps: [
      "Mix flour, water and starter; rest 30 minutes.",
      "Add salt and fold in. Do four sets of stretch-and-folds over 2 hours.",
      "Bulk ferment until risen by half, about 4 more hours.",
      "Shape, then proof in the fridge overnight.",
      "Bake in a preheated Dutch oven at 245°C: 20 min covered, 25 min uncovered.",
    ],
  },
  {
    slug: "focaccia",
    name: "Olive Oil Focaccia",
    tagline: "Dimpled, golden and pooled with good oil.",
    time: "14 hrs (20 min hands-on)",
    yield: "1 pan, about 12 pieces",
    difficulty: "Easy",
    ingredients: [
      "500 g bread flour",
      "400 g water",
      "10 g fine sea salt",
      "3 g instant yeast",
      "80 ml extra-virgin olive oil, divided",
      "Flaky salt and rosemary, to finish",
    ],
    steps: [
      "Stir flour, water, salt and yeast into a shaggy dough.",
      "Rest 12 hours in the fridge, covered, with 2 tbsp oil.",
      "Tip into an oiled pan, stretch, and let rise 2 hours.",
      "Dimple with oiled fingers; top with flaky salt and rosemary.",
      "Bake at 230°C for 22–25 minutes until deep golden.",
    ],
  },
  {
    slug: "chocolate-chip-cookies",
    name: "Chocolate Chip Cookies",
    tagline: "Brown butter, crisp edges, molten middles.",
    time: "1 hr 15 min (includes chilling)",
    yield: "16 cookies",
    difficulty: "Easy",
    ingredients: [
      "170 g unsalted butter, browned and cooled",
      "150 g brown sugar",
      "100 g granulated sugar",
      "1 egg plus 1 yolk",
      "2 tsp vanilla extract",
      "260 g all-purpose flour",
      "1 tsp baking soda",
      "1 tsp fine sea salt",
      "250 g dark chocolate, chopped",
    ],
    steps: [
      "Whisk the browned butter with both sugars, then the eggs and vanilla.",
      "Fold in flour, baking soda and salt, then the chocolate.",
      "Chill the dough for 1 hour.",
      "Scoop into 16 balls and bake at 180°C for 11–13 minutes.",
      "Finish with flaky salt and cool on the tray for 5 minutes.",
    ],
  },
];
